//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSIXProject1
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siemens.VSPackageTest.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between lines .
        /// </summary>
        internal static string Check_Between_Lines {
            get {
                return ResourceManager.GetString("Check_Between_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,1): Duplicate found between lines .
        /// </summary>
        internal static string Check_Duplicate_found_between_lines {
            get {
                return ResourceManager.GetString("Check_Duplicate_found_between_lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  in .
        /// </summary>
        internal static string Check_in {
            get {
                return ResourceManager.GetString("Check_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simian is not free unless used solely for non-commercial or evaluation purposes..
        /// </summary>
        internal static string Exception_01 {
            get {
                return ResourceManager.GetString("Exception_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity .
        /// </summary>
        internal static string Exception_02 {
            get {
                return ResourceManager.GetString("Exception_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Simon Harris..
        /// </summary>
        internal static string Exception_03 {
            get {
                return ResourceManager.GetString("Exception_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Project or Solution Found.
        /// </summary>
        internal static string VSPackageTestPackage_MenuItemCallback_No_Project_or_Solution {
            get {
                return ResourceManager.GetString("VSPackageTestPackage_MenuItemCallback_No_Project_or_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open a Solution or Project and try again..
        /// </summary>
        internal static string VSPackageTestPackage_MenuItemCallback_Please_Open_a_Solution_or_project_and_Click_again_ {
            get {
                return ResourceManager.GetString("VSPackageTestPackage_MenuItemCallback_Please_Open_a_Solution_or_project_and_Click" +
                        "_again_", resourceCulture);
            }
        }
    }
}
